# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_record_month', models.CharField(max_length=100)),
                ('purchase_record_date', models.CharField(max_length=100)),
                ('purchase_record_time', models.CharField(max_length=100)),
                ('purchase_record_id', models.IntegerField()),
                ('purchase_record_lottery_number', models.CharField(max_length=500)),
                ('purchase_record_rule', models.CharField(max_length=100)),
                ('purchase_record_money', models.IntegerField()),
                ('purchase_record_column', models.IntegerField()),
                ('purchase_record_value', models.IntegerField()),
            ],
        ),
    ]
