# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_visit', '0002_purchaserecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseRecord',
        ),
    ]
