# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_visit', '0007_fiancerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FianceRecord',
        ),
    ]
