# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_visit', '0008_delete_fiancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FianceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiance_record_month', models.CharField(max_length=100)),
                ('fiance_record_date', models.CharField(max_length=100)),
                ('fiance_record_time', models.CharField(max_length=100)),
                ('fiance_record_id', models.IntegerField()),
                ('fiance_record_lottery_number', models.CharField(max_length=500)),
                ('fiance_record_rule_id', models.CharField(max_length=100)),
                ('fiance_record_rule', models.CharField(max_length=100)),
                ('purchase_record_column', models.CharField(max_length=100)),
                ('fiance_record_value', models.IntegerField()),
                ('fiance_record_value_desc', models.CharField(max_length=100)),
                ('fiance_record_money', models.FloatField()),
                ('fiance_record_odds', models.FloatField()),
                ('fiance_record_profit', models.FloatField()),
                ('fiance_lose_win', models.IntegerField()),
            ],
        ),
    ]
