# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('append_predict', '0002_auto_20180520_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='killpredict',
            name='input_money',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
