# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('append_predict', '0003_killpredict_input_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='killpredict',
            name='save_predict_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
