# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('append_predict', '0004_killpredict_save_predict_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killpredict',
            name='gain_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
