# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('append_predict', '0005_auto_20180522_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killpredict',
            name='gain_money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='killpredict',
            name='xiazhu_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
