# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('append_predict', '0006_auto_20180523_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killpredict',
            name='input_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
