# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-25 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('append_predict', '0007_auto_20180523_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='killpredict',
            name='percent_all_list_desc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
