# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KillPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_predict_date', models.CharField(max_length=100)),
                ('kill_predict_time', models.CharField(max_length=100)),
                ('lottery_id', models.IntegerField()),
                ('kill_predict_number', models.CharField(max_length=200)),
                ('kill_predict_number_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('lottery_number', models.CharField(max_length=200)),
                ('predict_total', models.IntegerField(blank=True, null=True)),
                ('target_total', models.IntegerField(blank=True, null=True)),
                ('predict_accuracy', models.FloatField(blank=True, null=True)),
                ('predict_number_all', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KillPredictTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_predict_date', models.CharField(max_length=100)),
                ('kill_predict_time', models.CharField(max_length=100)),
                ('lottery_id', models.IntegerField(blank=True, null=True)),
                ('kill_predict_number', models.CharField(max_length=200)),
                ('lottery_number', models.CharField(max_length=200)),
                ('predict_total', models.IntegerField(blank=True, null=True)),
                ('target_total', models.IntegerField(blank=True, null=True)),
                ('predict_accuracy', models.FloatField(blank=True, null=True)),
                ('predict_column_number', models.IntegerField(blank=True, null=True)),
                ('predict_column_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PredictLottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_month', models.CharField(max_length=100)),
                ('lottery_date', models.CharField(max_length=100)),
                ('lottery_time', models.CharField(max_length=100)),
                ('lottery_id', models.IntegerField()),
                ('lottery_number', models.CharField(max_length=500)),
            ],
        ),
    ]
