# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_predictlottery'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillPredictTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_predict_date', models.CharField(max_length=100)),
                ('kill_predict_time', models.CharField(max_length=100)),
                ('lottery_id', models.IntegerField(blank=True, null=True)),
                ('kill_predict_number', models.CharField(max_length=200)),
                ('lottery_number', models.CharField(max_length=200)),
                ('predict_total', models.IntegerField(blank=True, null=True)),
                ('target_total', models.IntegerField(blank=True, null=True)),
                ('predict_accuracy', models.FloatField(blank=True, null=True)),
                ('predict_column_number', models.IntegerField(blank=True, null=True)),
                ('predict_column_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='killpredict',
            name='predict_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='killpredict',
            name='predict_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='killpredict',
            name='target_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
