# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-01 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_killpredict'),
    ]

    operations = [
        migrations.AddField(
            model_name='killpredict',
            name='gain_money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='killpredict',
            name='xiazhu_money',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
