# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20180202_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KillPredict',
        ),
    ]
