# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-01 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_auto_20180401_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('user_status', models.BooleanField()),
            ],
        ),
    ]
